services:

  stats-service:
    build:
      context: .
      dockerfile: ./stats/stats-service/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: statservice
      SPRING_DATASOURCE_PASSWORD: statservice
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    networks:
      - explore-with-me-network

  stats-db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: statservice
      POSTGRES_PASSWORD: statservice
      POSTGRES_DB: stats
    ports:
      - "5420:5432"
    networks:
      - explore-with-me-network

  main-service:
    build:
      context: .
      dockerfile: ./main-service/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://main-db:5432/main
      SPRING_DATASOURCE_USERNAME: mainservice
      SPRING_DATASOURCE_PASSWORD: mainservice
    ports:
      - "8080:8080"
    depends_on:
      - main-db
    networks:
      - explore-with-me-network

  main-db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: mainservice
      POSTGRES_PASSWORD: mainservice
      POSTGRES_DB: main
    ports:
      - "5430:5432"
    networks:
      - explore-with-me-network

networks:
  explore-with-me-network:
    driver: bridge