services:
  stats-server:
    build:
      context: .
      dockerfile: ./stat-service/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: statservice
      SPRING_DATASOURCE_PASSWORD: statservice
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    networks:
      - stats-network

  stats-db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: statservice
      POSTGRES_PASSWORD: statservice
      POSTGRES_DB: stats
    ports:
      - "5432:5432"
    networks:
      - stats-network

networks:
  stats-network:
    driver: bridge